# FIXME: smrsh
# FIXME: aliases
# FIXME: SAFE_FILE_ENV

- name: Install Sendmail packages
  ansible.builtin.apt:
    name:
      - "sendmail"
      - "sendmail-cf"
  notify: Restart Sendmail

- name: Deploy Sendmail configuration files
  vars:
    mc_daemons: "{{ sendmail_mc_daemons_default | ansible.builtin.combine(sendmail_mc_daemons, recursive=true) }}"
    access_table: "{{ sendmail_access_table_default | ansible.builtin.combine(sendmail_access_table) }}"
  ansible.builtin.template:
    src: "templates/sendmail/{{ item }}"
    dest: "/etc/mail/{{ item }}"
    mode: "0644"
  loop:
    - "access"
    - "domains"
    - "local-host-names"
    - "sendmail.conf"
    - "sendmail.mc"
    - "submit.mc"
    - "trusted-users"
  notify: Restart Sendmail

- name: Deploy Sendmail sasl.m4 file
  when: sendmail_mc_sasl
  ansible.builtin.template:
    src: "templates/sendmail/sasl.m4"
    dest: "/etc/mail/sasl/sasl.m4"
    mode: "0644"
  notify: Restart Sendmail

- name: Deploy Sendmail starttls.m4 file
  when: sendmail_mc_tls
  ansible.builtin.template:
    src: "templates/sendmail/starttls.m4"
    dest: "/etc/mail/tls/starttls.m4"
    mode: "0644"
  notify: Restart Sendmail

- name: Deploy Sendmail genericstable files
  when: sendmail_mc_generics
  vars:
    generics_table: "{{ sendmail_generics_table }}"
  ansible.builtin.template:
    src: "templates/sendmail/genericstable"
    dest: "/etc/mail/genericstable"
    mode: "0644"
  notify: Restart Sendmail

- name: Create Sendmail relay-domains files
  ansible.builtin.copy:
    dest: "/etc/mail/relay-domains"
    content: ""
    mode: "0644"
  notify: Restart Sendmail

- name: Link SASL configuration file
  when: sendmail_mc_sasl
  ansible.builtin.file:
    src: "/etc/mail/sasl/Sendmail.conf.2"
    dest: "/usr/lib/sasl2/Sendmail.conf"
    state: "link"

- name: Unlink SASL configuration file
  when: not sendmail_mc_sasl
  ansible.builtin.file:
    dest: "/usr/lib/sasl2/Sendmail.conf"
    state: "absent"

- name: Enable Sendmail service
  ansible.builtin.service:
    name: "sendmail"
    state: "started"
    enabled: true
