- name: Include distribution specific variables
  ansible.builtin.include_vars: "vars/distrib_{{ ansible_os_family }}.yml"

- name: Install ClamAV
  when: sendmail_clamav
  ansible.builtin.include_tasks: "install-clamav.yml"

- name: Install OpenDKIM
  when: sendmail_opendkim
  ansible.builtin.include_tasks: "install-opendkim.yml"

- name: Install Sendmail
  ansible.builtin.include_tasks: "install-sendmail.yml"
