- name: Restart ClamAV
  ansible.builtin.service:
    name: "{{ item }}"
    state: "restarted"
  loop:
    - "clamav-daemon"
    - "clamav-freshclam"
    - "clamav-milter"

- name: Restart OpenDKIM
  ansible.builtin.service:
    name: "opendkim"
    state: "restarted"

- name: Compile Sendmail config
  listen: Restart Sendmail
  changed_when: true
  ansible.builtin.shell:
    chdir: "/etc/mail"
    cmd: |
      /usr/share/sendmail/update_mc
      /usr/share/sendmail/update_db
      /usr/share/sendmail/update_sendmail
      make

- name: Restart service Sendmail
  listen: Restart Sendmail
  ansible.builtin.service:
    name: "sendmail"
    state: "restarted"
